config/routes.rb
Inedite::Application.routes.draw do
  resources :articles, :paniers, :clothes

  devise_for :users

  get "users/new"

  root to: 'static_pages#home'

  match '/users/:id',  to: 'users#show'
  match '/signup',  to: 'users#new'
  match '/gestionUser', to: 'users#gestionUser'

  match '/panier', to: 'paniers#index'
  match '/add', to: 'paniers#add'
  match '/flush', to: 'paniers#flush'
  match '/edit', to: 'paniers#edit'
  match '/destroy', to: 'paniers#destroy'
  match '/gestionPanier', to: 'paniers#gestionPanier'

  match '/categories', to: 'articles#cat' #OK
  match '/gestionArticle', to: 'articles#gestionArticle'
  match '/edit', to: 'articles#edit'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/admin', to: 'static_pages#admin'

  match '/create', to: 'clothes#create'
  match '/delete', to: 'clothes#delete'
  
  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :nom, :prenom,:adresse,:email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
 has_many :paniers, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def gestionUser
  	@users = User.all
  end
 
  def show
    @user = User.find(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/gestionUser.html.erb
<div id="corps">
<style>
th{
	color: green;
}

td {
	border: solid black 1px;
}

</style>



<h1>Bienvenue sur la page de gestion des clients</h3>

	<table>
  		<tr>
	       	<th>Id</th>
	       	<th>Nom</th>
	       	<th>Prenom</th>
	       	<th>Mail</th>
	       	<th>Adresse</th>
	       	<th>Date d'inscription</th>
	       	<th>Ses paniers</th>
	       	<th>Admin</th>
	       	<th>Bannir</th>
	       		       	
	  	</tr>

	  		<% @users.each do |u| %>

<% @pan = Panier.where('user_id' => u.id) %>

	  	
	  			<tr>
			       	<td> <li><a href="/users/<%=u.id%>"><%=u.id%></a></li>
			    
			       	<td> <%= u.nom %> 
			    
			       	<td> <%= u.prenom %>
			    
			       	<td> <%= u.email %>

			       	<td> <%= u.adresse %>

			       	<td> <%= u.created_at %>

			       	<td> 	Nombre de panier:<%= @pan.length %><br />
			       			Dernier panier: 
			       			<li><%= link_to @pan.last.id,   panier_path(@pan.last.id) %></li>

			       	<td> <%= u.admin %>

	        		<td>
	        			<%= form_tag("/delete", method: "get") do %>        				
					  	<%= hidden_field_tag(:id, u.id) %>
					  	<%= submit_tag("Bannir") %>
						<% end %>
				</tr>
		
			<% end %>
	</table>

</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div id="corps">
<a href = "/gestionUser">Visualiser tous les clients</a><br />

<% if @user.admin? %>
<h1>Profil de <%= @user.nom%> <%= @user.prenom %> (Admin)</h1>
<p>
	Cette personne possède les droits d'administrateurs sur le site
<p>
<% else %>
<h1>Profil de <%= @user.nom%> <%= @user.prenom %></h1>
<p>
	Cette personne n'est pas un administrateur
</p>
<% end %>

<h3>Informations du client</h3>
<p>
	Numéro client : <%= @user.id %><br />
	Nom : <%= @user.nom %><br />
	Prenom : <%= @user.prenom %><br />
	E-mail : <%= @user.email %><br />
	Adresse : <%= @user.adresse %><br />
	<% ins = @user.created_at %>
	Date d'inscription : <%= ins.strftime("%d/%m/%Y") %><br />
</p>

<% @pan = Panier.where('user_id' => @user.id) %>
<h3>Ses paniers: <%= @pan.length %></h3>
<p>
	<% @pan.each do |p| %>
		<% date = p.created_at %>
		<% dateb = date.strftime("%d/%m/%Y") %>

		<li><%= link_to p.id,   panier_path(p.id) %></li> Creer le <%= dateb %> 
		<% if p.validated? %>
			Validé
		<% else %>
			Non validé
		<% end %>
		<br />

	<% end %>
</p>

	<%= form_tag("/delete", method: "get") do %>        				
	  	<%= hidden_field_tag(:id, @user.id) %>
	  	<%= submit_tag("Bannir") %>
	<% end %>

</div>