config/routes.rb
Inedite::Application.routes.draw do
  resources :articles, :paniers, :clothes

  devise_for :users

  get "users/new"

  root to: 'static_pages#home'

  match '/users/:id',  to: 'users#show'
  match '/signup',  to: 'users#new'
  match '/gestionUser', to: 'users#gestionUser'

  match '/panier', to: 'paniers#index'
  match '/add', to: 'paniers#add'
  match '/flush', to: 'paniers#flush'
  match '/edit', to: 'paniers#edit'
  match '/destroy', to: 'paniers#destroy'
  match '/gestionPanier', to: 'paniers#gestionPanier'

  match '/categories', to: 'articles#cat' #OK
  match '/gestionArticle', to: 'articles#gestionArticle'
  match '/edit', to: 'articles#edit'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/admin', to: 'static_pages#admin'

  match '/create', to: 'clothes#create'
  match '/delete', to: 'clothes#delete'
  
  

end

app/views/layouts/_footer.html.erb
<div id="footer">

<footer class="navbar navbar-fixed-bottom navbar-inverse">
  <div class="bouton">
        <ul class="nav pull-right">
            <li><%= link_to "About",   about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
        </ul>



</footer>
</div>

app/views/layouts/_header.html.erb
<div id= "banniere">
  <header class="navbar navbar-fixed-top navbar-inverse"> 
    <nav>
       
 <div id="titre">
                <%= image_tag("logoinedite.png", :size => "300x300") %>
        </div>
        <div class="bouton">
            <ul>

              <li class="first"><%= link_to "Help",    help_path %></li>
              <li><%= link_to "Home",    root_path %></li>
             <li>
                <%= link_to "Panier", '/panier', :class => 'navbar-link'  %>
              </li>
              <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>

            </ul>
         </div> 
      

        <% if user_signed_in? %>

         
            <div class = "mail">
              <ul>
                <h5><li>Logged in as <strong ><%= current_user.email %></strong></li></h5>
                <h5>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li> 
                </h5>
              </ul>
            </div>
           

           
         
             
        <% else %>

            <div class="mail">
              <ul>
                <h5>
                <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li></h5>
                <h5>
                <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li></h5>
              </ul>
            </div>
          

        <% end %>
        

      

      

        </nav>
    </header>
</div>

<div id="transition-header">
</div>

app/views/layouts/_nav.html.erb
<div id = "aside">

	<ul class="nav-list">
		<% cats = Article.all.map { |a| a.type_art } %>
		<% cat = cats.uniq!.sort %>
		<br />
	    <li class="nav-header"><span>Catégories :</span></li> <br />
	    <% cat.each do |c| %>
	        <li><a href="/categories/?type=<%=c%>"><%= c%></a></li>
	    <%end%>
	    <li><a href="/articles"><span>Tous les articles</span></a></li>

	              </ul>
	

</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 
  <head>
    <title><%= full_title(yield(:title)) %></title>
      <%= stylesheet_link_tag    "application", media: "all" %>
      <%= javascript_include_tag "application" %>
      <%= csrf_meta_tags %>
      <%= render 'layouts/shim' %>    
  </head>
  
  <body>
    
    <div id="page">
    
    <!--Ajout du header par ruby-->
      <div id="banniere">
        <%= render 'layouts/header' %>
      </div>

      <div class="container-fluid">
      
      <div class="flash">
        <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><strong><%= value %></strong></div>
        <% end %>
      </div>

        <div class="row-fluid">
          <%= render 'layouts/nav' %>
          <!-- Corp de page -->

          <div id="grossepage">
            <div class="body">
              <%= yield %>
            </div>
              <div id="dernier-element">
             </div>
          </div>
        </div>

        <!--Ajout du footer par ruby-->
        <%= render 'layouts/footer' %>
      </div>

    </div>
  
  </body>
</html>